### ISSUE TITLE
Connect Rescue Routes to Food Rescue Component

### ISSUE THREAD

**Issue by bluek1te** [bluek1te/feed-txstate#1]
Connect Rescue-Angular to Rescue-Express

**Comment by bluek1te** [comment]
Hey Ben, I uploaded my whole senior design directory to a public repo and you should be able to access everything now.
https://github.com/bluek1te/coursebrew

**Comment by BenjaminWalkerBond** [comment]
Thanks so much. It’s already helping me a lot.

**Comment by bluek1te** [comment]
Can we merge your current branch into develop btw

**Comment by BenjaminWalkerBond** [comment]
We cannot merge it yet. Need to test one more function in the distribution controller and then we can. I also have a stray button in the rescue route that I was using for testing that I need to remove. Give me two days.

**Comment by bluek1te** [comment]
#12 Merged, closing
