### ISSUE TITLE
Update dependencies for latest Node

### ISSUE THREAD

**Issue by bluek1te** [bluek1te/feed-txstate#6]
A few packages we use (ex. Sass) are incompatible with the latest version of Node. Putting this in as a reminder for myself to go through all of the packages we use to update their versions. Also need to remove packages we no longer use (Such as Apollo)

**Comment by smashwilson** [comment]
[Dependabot](https://dependabot.com/) is great for keeping dependencies up to date btw, especially once we have CI in place :smile:

**Comment by bluek1te** [comment]
https://github.com/bluek1te/feed-txstate/commit/d65ee65795824d1d19df7e57d41943c0a96a8c44
